### ISSUE TITLE
provide silence button for site-done alerts

### ISSUE THREAD

**Issue by sdaugherty** [QQHeresATissue/ERA#4]
The "site done" alerts are amazing, but if I've intentionally stopped my ratting session they become very annoying.

A snooze button for these alerts would make them more palatable, and keep users from needing to shut down the monitor to preserve their sanity. The alerts should automatically reenable once damage notifications indicate resumption of ratting.

**Comment by QQHeresATissue** [comment]
Agreed.  I often run into this as well, and think that switching to multiprocessing vs threading will help.  We should be able to just hit the button again to stop the processing, and start it back up when were ready.  I have ideas for this, just haven't had a chance to implement them.

**Comment by QQHeresATissue** [comment]
Implemented this without automatic re-enabling.  Moving through gates and taking rat damage would re-enable.  A simple start/stop state went in instead.
